STRING = "STRING"
NUMBER = "NUMBER"
LBRACE = "LBRACE"
RBRACE = "RBRACE"
LBRACKET = "LBRACKET"
RBRACKET = "RBRACKET"
COLON = "COLON"
COMMA = "COMMA"
SKIP = "SKIP"
EOF = "EOF"

END_OF_FILE_EXCEPTION = "Unexpected end of file"
FIRST_TOKEN_EXCEPTION = "Expceted '[' or '{' at the beginning of the file"
EMPTY_INPUT_EXCEPTION = "Empty File"

JSON_SYNTAX_ERROR = "JSON syntax error"
EXPECTED = "Expected token: "
UNEXPECTED_TOKEN = "Unexpected token"